In [13]:
import numpy

In [8]:
inp = raw_input()

1 2 3 4 5


## reverse array

In [38]:
arr = inp.strip().split(' ')

In [39]:
arr

['1', '2', '3', '4', '5']

In [40]:
def arrays(arr):
    #print(arr)
    arr.reverse()
    return(numpy.array(arr,float))


In [41]:
arrays(arr)

array([ 5.,  4.,  3.,  2.,  1.])

In [19]:
?numpy.array

## Reshape the array

In [43]:
arr2 = raw_input().strip().split(' ')

1 2 3 4 5 6 7 8 9


In [50]:
numpy.array(arr2).shape

(9,)

In [48]:
print numpy.reshape(numpy.array(arr2,int),(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
?numpy.array

## Transpose and Flatten array

In [53]:
dim = raw_input().strip().split(' ')

2 3


In [54]:
print dim

['2', '3']


In [58]:
dim = numpy.array(dim,int)

In [59]:
dim

array([2, 3])

In [55]:
print ('Enter array elements')

Enter array elements


In [56]:
ar = raw_input().strip().split(' ')

1 2 3 4 5 6


In [57]:
print ar

['1', '2', '3', '4', '5', '6']


In [61]:
new_ar = numpy.array(ar,int)

In [64]:
new_ar = new_ar.reshape(dim)

In [65]:
print numpy.transpose(new_ar)

[[1 4]
 [2 5]
 [3 6]]


In [67]:
print new_ar.flatten()

[1 2 3 4 5 6]


### Different approach

In [69]:
n, m = map(int, raw_input().strip().split())

2 3


In [70]:
print (n, m)

(2, 3)


In [74]:
my_arr = numpy.array([raw_input().strip().split(' ') for _ in range(n)], int)

1 2 3
4 5 6


In [75]:
print my_arr

[[1 2 3]
 [4 5 6]]


In [76]:
print my_arr.transpose()

[[1 4]
 [2 5]
 [3 6]]


In [77]:
print my_arr.flatten()

[1 2 3 4 5 6]


### Concatenate arrays

In [78]:
# arr1 NxP
# arr2 MxP
# result is contatenated array along axis 0, ie., (N+M)xP

In [83]:
# input order is N rows, M rows and P columns
n, m, p = map(int, raw_input().strip().split(' '))

3 4 2


In [84]:
print(n, m, p)

(3, 4, 2)


In [85]:
# read the array
arr1 = numpy.array([raw_input().strip().split(' ') for _ in range(n) ], int)

1 2
1 2
1 2


In [87]:
# read the second array
arr2 = numpy.array([raw_input().strip().split() for _ in range(m)] ,int)

3 4
3 4
3 4
3 4


In [91]:
### concatenate row wise
print( arr1, arr2)
print( numpy.concatenate((arr1, arr2), axis =0))

(array([[1, 2],
       [1, 2],
       [1, 2]]), array([[3, 4],
       [3, 4],
       [3, 4],
       [3, 4]]))
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]


In [90]:
?numpy.concatenate

## Zeros & Ones

In [92]:
?numpy.zeros

In [94]:
numpy.zeros((3,3,3), int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [95]:
numpy.ones((3,3,3), int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [98]:
# get the dimensions
dim_arr = numpy.array(raw_input().strip().split(' '), int)

3 3 3


In [99]:
print dim_arr

[3 3 3]


In [100]:
print numpy.ones(dim_arr, int)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [101]:
print numpy.zeros(dim_arr, int)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


## Identity

In [111]:
n, m = map(int, raw_input().strip().split())

3 3


In [112]:
print n, m

3 3


In [113]:
print numpy.identity(n)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [117]:
#numpy.dtype(n)

In [118]:
#?numpy.eye
print( numpy.eye(n,m, k=0))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [119]:
print (numpy.eye(n, m , k = 1))

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [120]:
# lower diagonal
print (numpy.eye(n, m , k = -1))

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]


## Matrix operations

In [121]:
# get the matrix dimensions
n, m = map(int, raw_input().strip().split())

2 2


In [122]:
# read the array
arr1 = numpy.array( [raw_input().strip().split() for _ in range(n)],int)

1 2
3 4


In [123]:
# array 2
arr2 = numpy.array( [raw_input().strip().split() for _ in range(n)],int)

5 6
7 8


In [137]:
print(arr1, arr2)

(array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]))


In [138]:
print( arr1+arr2)
print( arr1-arr2)
print( arr1*arr2)
print( arr1//arr2)
print( arr1%arr2)
print( arr1**arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0 0]
 [0 0]]
[[1 2]
 [3 4]]
[[    1    64]
 [ 2187 65536]]


In [133]:
?print

Object `print` not found.


## Floor, Ceil and Rint

In [139]:
# get the input
arr = numpy.array(raw_input().strip().split(' ') ,float)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


In [142]:
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod

In [143]:
# sum provides the sum for the given axis
# axis 0 => columwise
# axis 1 => rowwise
# none => all elements
n,m = map(int, raw_input().strip().split())

2 2


In [144]:
# read the array
arr = numpy.array([raw_input().strip().split(' ') for _ in range(n)] ,int)

1 2
3 4


In [148]:
# use axis 0
sum_arr = numpy.sum(arr, axis=0)

print(sum_arr)
#print(numpy.prod(arr, axis=0))
# get the product of the sum_arr
print( numpy.prod(sum_arr))

[4 6]
24


## Min and Max

In [149]:
# axis 0 => columwise
# axis 1 => rowwise
# none => all elements

In [150]:
n,m = map(int, raw_input().strip().split())

4 2


In [151]:
# read the array
arr = numpy.array([raw_input().strip().split(' ') for _ in range(n)] ,int)

1 2
3 4
5 6
7 8


In [152]:
# Compute the min along axis =1 and then print the max of that result.
min_arr = numpy.min(arr, axis =1)
print(numpy.max(min_arr))

7


## Mean, Variance and Std Deviation

In [153]:
# axis 0 => columwise
# axis 1 => rowwise
# none => all elements

In [154]:
n,m = map(int, raw_input().strip().split())
# read the array
arr = numpy.array([raw_input().strip().split(' ') for _ in range(n)] ,int)

2 2
1 2
3 4


In [155]:
# The mean along axis 1
mean_arr = numpy.mean(arr, axis=1)
print(mean_arr)

[ 1.5  3.5]


In [156]:
# The var along axis 0
print(numpy.var(arr, axis=0))

[ 1.  1.]


In [158]:
# The std along axis None
print(numpy.std(arr, axis=None))

1.11803398875
