## Implementation Details

The OpenCV library has many modules [http://docs.opencv.org/3.2.0/]. Few are as follows:

1. Core Modules : Basic Data structures - Mat
2. Video


* The image is evetually stored as a collection of numbers. To be precise, it is a matrix of numbers.

* In the case of gray scale images, there is only one channel with range of values from 0 to 255.
* Whereas, for the color image, there are **3 channels, Red, Green and Blue**.

* They are stored in the data structure called **Mat** which is a N-dimensional dense array.
* When the Mat object is passed around, it won't make a copy instead uses **reference count mechanism** to optimize the memory usage.
* The API imread() reads the image and populates the Mat object in the **reverse order, ie., B, G, R**.

## Additional Resources

1.[Why does opencv use B, G, R format?](https://www.learnopencv.com/why-does-opencv-use-bgr-color-format/)

In [1]:
import numpy as np
import cv2

In [2]:
cv2.__version__

'3.1.0'

In [2]:
img = cv2.imread('./hello.jpeg', 0)

In [3]:
# img is a Mat
print(img)

[[243 243 243 ..., 243 243 243]
 [243 243 243 ..., 243 243 243]
 [243 243 243 ..., 243 243 243]
 ..., 
 [243 243 243 ..., 243 243 243]
 [243 243 243 ..., 243 243 243]
 [243 243 243 ..., 243 243 243]]


In [4]:
print(img.shape)

(142, 354)


In [8]:
print(img[75,])

[243 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243
 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243
 243 243 243 243 252 147  91 115 173 145 163 150 154 154 154 154 154 154
 154 154 140 152 143 155 146 177 196 197 205  66  24  22   9  98 218 248
 248 237 240 252 237 239 246 208 195 194 194 170  13  35  80   0  11   7
   1   0   0   0   5   9  59  32  34   0  61   2   6   0   0   0   4   1
   0   0   2  42 186 218 168 200 198 192  12 117 224 244 239 241 245 241
 245 241 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243 243
 237 240 244 248 249 248 247 245 248 255 241 244 129  82  85  84  98  99
  99  98  96  93  89  88  95  91  91  83  91  99  86 202 243 221 233 218
  30  94 214 244 243 243 243 243 243 243 243 243 243 243 243 243 243 243
 243 243 239 249 196 206 184 226 217 228 226 226 226 226 226 226 226 226
 222 221 222 220 222 209 189 200 204 182  44  35  91 174 240 240 243 243
 243 243 243 243 243 243 240 238 242 242 240 247 24

In [11]:
## let's read a color image
colr_img = cv2.imread('./hello.jpeg', cv2.IMREAD_COLOR)

In [12]:
print(colr_img.shape)

(142, 354, 3)


There are three channels for this color image of size 142x354 pixels.

In [15]:
print(colr_img)

[[[153 255 254]
  [153 255 254]
  [153 255 254]
  ..., 
  [153 255 254]
  [153 255 254]
  [153 255 254]]

 [[153 255 254]
  [153 255 254]
  [153 255 254]
  ..., 
  [153 255 254]
  [153 255 254]
  [153 255 254]]

 [[153 255 254]
  [153 255 254]
  [153 255 254]
  ..., 
  [153 255 254]
  [153 255 254]
  [153 255 254]]

 ..., 
 [[153 255 254]
  [153 255 254]
  [153 255 254]
  ..., 
  [153 255 254]
  [153 255 254]
  [153 255 254]]

 [[153 255 254]
  [153 255 254]
  [153 255 254]
  ..., 
  [153 255 254]
  [153 255 254]
  [153 255 254]]

 [[153 255 254]
  [153 255 254]
  [153 255 254]
  ..., 
  [153 255 254]
  [153 255 254]
  [153 255 254]]]


In [16]:
print(colr_img[0], colr_img[1], colr_img[2])

(array([[153, 255, 254],
       [153, 255, 254],
       [153, 255, 254],
       ..., 
       [153, 255, 254],
       [153, 255, 254],
       [153, 255, 254]], dtype=uint8), array([[153, 255, 254],
       [153, 255, 254],
       [153, 255, 254],
       ..., 
       [153, 255, 254],
       [153, 255, 254],
       [153, 255, 254]], dtype=uint8), array([[153, 255, 254],
       [153, 255, 254],
       [153, 255, 254],
       ..., 
       [153, 255, 254],
       [153, 255, 254],
       [153, 255, 254]], dtype=uint8))
